[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solanavotingapp = "3bpJKXpciNCFRJ96wR8VbjNR94ahAEkENU8qsCwgPTWh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx vitest run"
